In [1]:
#Naive_Bayes_Classifier on IRIS Dataset 
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("IRIS.csv")
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
#Spliting dependent and independent variables Y is Target Attribute which is species.
X =df.iloc[0:,:4].values
Y = df['species'].values

In [4]:
#Spliting Data for traning(80%) and testing(20%)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.20)

In [5]:
#Featrure scaling to bring variable in a single scale
import time
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
start=time.time()
X_train = sc.fit_transform(X_train)
stop= time.time()
print(f"Training time: {stop - start}s")
start=time.time()
X_test = sc.transform(X_test)
stop= time.time()
print(f"Testing time: {stop - start}s")
X_test

Training time: 0.00399470329284668s
Testing time: 0.00099945068359375s


array([[-0.5269063 ,  1.5523195 , -1.27111105, -1.31278766],
       [-0.88413091,  1.79113788, -1.21402523, -1.31278766],
       [ 1.14014187, -0.59704596,  0.6127212 ,  0.29197824],
       [-0.5269063 ,  2.02995626, -1.1569394 , -1.04532668],
       [-1.24135551, -0.11940919, -1.32819688, -1.17905717],
       [ 0.78291727, -0.59704596,  0.49854954,  0.42570873],
       [ 0.42569266,  0.83586434,  0.95523615,  1.49555267],
       [-0.16968169,  1.79113788, -1.1569394 , -1.17905717],
       [ 0.78291727, -0.11940919,  0.8410645 ,  1.09436119],
       [-1.00320577, -2.50759303, -0.12939454, -0.24294373],
       [ 1.61644135,  1.31350111,  1.35483693,  1.76301365],
       [ 0.18754292, -0.83586434,  0.78397867,  0.55943922],
       [ 0.54476753,  0.59704596,  1.2977511 ,  1.76301365],
       [-0.40783143, -1.5523195 ,  0.04186294, -0.10921323],
       [-0.88413091,  1.79113788, -1.27111105, -1.17905717],
       [ 2.2118157 , -1.07468273,  1.81152354,  1.49555267],
       [ 0.18754292, -0.

In [6]:
#Fitting Naive Bayes classification to the Training set
from sklearn.naive_bayes import GaussianNB
nbclassifier = GaussianNB()
nbclassifier.fit(X_train,y_train)

GaussianNB()

In [7]:
#Predicting the test set result
Y_pred= nbclassifier.predict(X_test)
Y_pred

array(['Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa'],
      dtype='<U15')

In [8]:
#Confusion Matrix diagonal values are Correct predidted values.
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,Y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [9]:
print(classification_report(y_test,Y_pred))


                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [10]:
#Accuracy is 0.93 percent
#ErrorRate=(1-Accuracy)=
1-0.93

0.06999999999999995

In [11]:
#Naive_Bayes_Classifier on Titanic Dataset 



In [12]:
#Clean the dataset Manually by converting Catagorical Attributes into 0 and 1, and removed unrequire Attributes e.g Name,Caben etc

In [28]:
import pandas as pd
train_dataset = pd.read_csv("train_data.csv",index_col=0)

In [29]:
train_dataset.head(3)

Pclass  Sex  Age  Fare  Embarked  Title  IsAlone
0       3    0    1     0         0      1        0
1       1    1    2     3         1      3        0
2       3    1    1     1         0      2        1

In [30]:
test_dataset = pd.read_csv("test_data.csv", index_col =0)

In [31]:
test_dataset.head(3)

Pclass  Sex  Age  Fare  Embarked  Title  IsAlone
0       3    0    2     0         2      1        1
1       3    1    2     0         0      3        0
2       2    0   62     1         2      1        1

In [32]:
test_labels = pd.read_csv("test_labels.csv",index_col=0)
train_labels = pd.read_csv("train_labels.csv",index_col=0)
train_labels.head(3)
test_labels.head(3)

Survived
0         0
1         1
2         0

In [40]:
#Featrure scaling to bring variable in a single scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
start=time.time()
train_dataset = sc.fit_transform(train_dataset)
stop=time.time()
print(f"Training time: {stop - start}s")
start=time.time()
test_dataset = sc.transform(test_dataset)
stop=time.time()
print(f"Testing time: {stop - start}s")
test_dataset

Training time: 0.001999378204345703s
Testing time: 0.0009984970092773438s


array([[ 0.82816049, -0.73833521, -0.22749444, ...,  2.59034684,
        -0.70814698,  0.81267937],
       [ 0.82816049,  1.35439836, -0.22749444, ..., -0.56774725,
         1.23407432, -1.23049758],
       [-0.36837009, -0.73833521,  4.01419659, ...,  2.59034684,
        -0.70814698,  0.81267937],
       ...,
       [ 0.82816049, -0.73833521, -0.22749444, ..., -0.56774725,
        -0.70814698,  0.81267937],
       [ 0.82816049, -0.73833521, -0.22749444, ..., -0.56774725,
        -0.70814698,  0.81267937],
       [ 0.82816049, -0.73833521, -0.22749444, ...,  1.01129979,
         2.20518498, -1.23049758]])

In [34]:
#Fitting Naive Bayes classification to the Training set
from sklearn.naive_bayes import GaussianNB
nvclassifier = GaussianNB()
nvclassifier.fit(train_dataset,train_labels)

C:\Users\4a\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [36]:
#Predicting the test set result
y_pred= nvclassifier.predict(test_dataset)
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,

In [41]:
#Confusion Matrix diagonal values are Correct predidted values.
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(test_labels,y_pred))

[[236  30]
 [134  18]]


In [49]:
print(classification_report(test_labels,y_pred))

              precision    recall  f1-score   support

           0       0.64      0.89      0.74       266
           1       0.38      0.12      0.18       152

    accuracy                           0.61       418
   macro avg       0.51      0.50      0.46       418
weighted avg       0.54      0.61      0.54       418



In [52]:
#Accuracy=TP+TN/Totall
(236+18)/418

0.6076555023923444